### PR TITLE
Added make_button_item() functions

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by TutorialDoctor** [comment]
Thanks clauss. I usually refine the code for readability iteratively. That was the quick and dirty method. I have a question, I haven't merged repos before, there seems to be a conflict. I would like to merge this though.

**Comment by cclauss** [comment]
Strange.  This is the second time since New Year's that I have seem GitHub say that there is a conflict that is not visible upon review.  If it allows you to override the "conflict" and accept the change anyway then please do so.

**Comment by TutorialDoctor** [comment]
I used `git mergetool` and I suppose the issues is within the read me file. I had reorganized some files and folders in the main repo, perhaps this is causing it.

**Comment by TutorialDoctor** [comment]
I just copied and pasted the code in the file. Thank you.

**Pull request closed without merging**
